[credentials]
# Insert the password for accessing the dashboard here
password = '<insert password here>'

# Configuration Settings
[config]
# Environment setting: 'development' for development mode, 'production' for production usage
# In development mode password is not required
environment = 'development'

# Debugging: Set to true to enable debug mode, false to disable it
debug = false

# Cache Configuration: Specifies the number of stocks per sector for which data will be cached
# count = 5 for development/testing, default is 10.
count = 5

# Sleep Time: Time in seconds to wait before the next cache update
sleep_time = 3300

# Logging Settings: Enable or disable detailed logging for various components
thread_details = false
cache_updater_details = false
cache_util_verbose_log = false
